/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package api.internals.evr;

public class evrJNI {
  public final static native long new_Math();
  public final static native void delete_Math(long jarg1);
  public final static native double Math_add(long jarg1, Math jarg1_, double jarg2, double jarg3);
}
